support webflux
sofastack/sofa-tracer pull request #228
Opened 2019-05-29 10:36 UTC by shengxiang205

### Motivation:

1. add sofa tracer reactor plugin
2. add tracer sample with webflux 

### Modification:

add reactor transaction to keep global sofa tracer span 
and keep and restore global sofa tracer span

### Result:

Fixes #227

2019-06-17 09:49 UTC, glmapper requested changes

2019-06-17 09:49 UTC, glmapper commented on pom.xml
> +        <reactor.version>3.2.6.RELEASE</reactor.version>
目前最新版本是 3.2.9 可以使用最新版本的

2019-06-17 09:49 UTC, glmapper commented on pom.xml
> +                <artifactId>sofa-tracer-reactor-plugin</artifactId>
这里的 reactor 之前是已经 remove 的，下沉到 core 中，这里是对于纯 reactor 埋点吗？

2019-06-17 09:49 UTC, glmapper commented on sofa-tracer-plugins/sofa-tracer-webflux-plugin/pom.xml
> +            <artifactId>sofa-tracer-springmvc-plugin</artifactId>
这里感觉不用依赖 springmvc 的插件，部分重复代码冗余一份，既然分开两个插件，就应该相互独立开

2019-06-17 09:49 UTC, glmapper commented on sofa-tracer-plugins/sofa-tracer-webflux-plugin/src/main/java/com/alipay/sofa/tracer/plugins/webflux/WebfluxSofaTracerFilter.java
> +            throwable != null ? new SofaStatusResponseDecorator(throwable, exchange.getResponse())
异常的话可以在tag 里面加一个 error 信息，这样上报的数据可以直观的看到异常情况

2019-06-17 09:49 UTC, glmapper commented on sofa-tracer-plugins/sofa-tracer-webflux-plugin/src/main/java/com/alipay/sofa/tracer/plugins/webflux/WebfluxSofaTracerFilter.java
> +            throwable != null ? new SofaStatusResponseDecorator(throwable, exchange.getResponse())
另外 import java.util.*; 这个不要使用 *

2019-06-17 09:49 UTC, glmapper commented on tracer-core/pom.xml
> +            <version>${reactor.version}</version>
可以管控在 主 pom 里面

2019-06-17 09:49 UTC, glmapper commented on tracer-core/src/main/java/com/alipay/common/tracer/core/reactor/FluxSofaOperator.java
> +    private final Runnable                                    startSpan;
命名不合理，xxxSpan 从语义上应该是一个 span，这里表示一个 Runnable 不太合理。比如 可以使用operatorStartRunnable   operatorFinishRunnable(供参考，具体可根据当前 Runnable 的含义进行定义)

2019-06-17 09:49 UTC, glmapper commented on tracer-core/src/main/java/com/alipay/common/tracer/core/reactor/FluxSofaOperator.java
> +
同上

2019-06-17 09:49 UTC, glmapper commented on tracer-core/src/main/java/com/alipay/common/tracer/core/reactor/MonoSofaOperator.java
> +    private final Runnable                                    startSpan;
同上

2019-06-17 09:49 UTC, glmapper commented on tracer-core/src/main/java/com/alipay/common/tracer/core/reactor/MonoSofaOperator.java
> +    private final BiFunction<SofaTracerSpan, Throwable, Void> finishSpan;
同上

2019-06-17 09:49 UTC, glmapper commented on tracer-core/src/main/java/com/alipay/common/tracer/core/reactor/MonoSofaOperator.java
> +            new SofaTracerReactorSubscriber<>(actual, this.startSpan, this.finishSpan, true));
这里面 source.log() 用意是什么呢

2019-06-17 09:49 UTC, glmapper commented on tracer-core/src/main/java/com/alipay/common/tracer/core/reactor/SofaTracerBarrier.java
> +    public static void runOnSofaTracerSpan(Runnable f,
变量命名不规范，问题同上

2019-06-17 09:49 UTC, glmapper commented on tracer-core/src/main/java/com/alipay/common/tracer/core/reactor/SofaTracerBarrier.java
> +            SofaTracerSpan newSpan = sofaTraceContext.getCurrentSpan();
newSpam->currentSpan

2019-06-17 09:49 UTC, glmapper commented on tracer-core/src/main/java/com/alipay/common/tracer/core/reactor/SofaTracerReactorConstants.java
> +    public static String SOFA_TRACER_CONTEXT_KEY = "sofa-tracer-context-key";
这个常量可以放在公共的常量类里或者放在具体使用的类中，不必单独用一个常量类来声明

2019-06-17 09:49 UTC, glmapper commented on tracer-core/src/main/java/com/alipay/common/tracer/core/reactor/SofaTracerReactorSubscriber.java
> +    private final Runnable                                    startSpan;
命名问题，同上

2019-06-17 09:49 UTC, glmapper commented on tracer-core/src/main/java/com/alipay/common/tracer/core/reactor/SofaTracerReactorSubscriber.java
> +    private final BiFunction<SofaTracerSpan, Throwable, Void> finishSpan;
命名问题，同上

2019-06-17 09:49 UTC, glmapper commented on tracer-core/src/main/java/com/alipay/common/tracer/core/reactor/SofaTracerReactorSubscriber.java
> +    private final boolean                                     unary;
unary 这个变量可以适当加一下注释，或者使用其他语义更加清晰的单词

2019-06-17 09:49 UTC, glmapper commented on tracer-core/src/main/java/com/alipay/common/tracer/core/reactor/SofaTracerReactorSubscriber.java
> +        SofaTracerBarrier.runOnSofaTracerSpan(f, this.sofaTracerSpanContainer);
变量命令不清晰，同上

2019-06-17 09:49 UTC, glmapper commented on tracer-core/src/main/java/com/alipay/common/tracer/core/reactor/SofaTracerReactorTransformer.java
> +    private final BiFunction<SofaTracerSpan, Throwable, Void> finishSpan;
同上

2019-06-17 09:49 UTC, glmapper commented on tracer-core/src/main/java/com/alipay/common/tracer/core/reactor/SofaTracerReactorTransformer.java
> +        this.finishSpan = finishSpan;
同上

2019-06-17 09:49 UTC, glmapper commented on tracer-core/src/main/java/com/alipay/common/tracer/core/reactor/SofaTracerSpanContainer.java
> +    private SofaTracerSpan value;
value-> span 或者 sofaTracerSpan

2019-06-17 09:49 UTC, glmapper commented on tracer-core/src/test/java/com/alipay/common/tracer/core/reactor/base/ReactorTracer.java
> +    public enum ReactorLogEnum {
建议和其他组件一样，移出去单独申明

2019-06-17 09:49 UTC, glmapper commented on tracer-core/src/test/java/com/alipay/common/tracer/core/reactor/base/ReactorTracer.java
> +        return generateSofaMvcStatReporter();
generateSofaMvcStatReporter 应该使用 类似 generateReactorStatReporter 命令

2019-06-17 09:49 UTC, glmapper commented on tracer-samples/tracer-sample-with-springwebflux/pom.xml
> +            <version>4.5.3</version>
版本放到 主pom 里面管控

2019-06-20 08:37 UTC, shengxiang205 commented on pom.xml
> +        <reactor.version>3.2.6.RELEASE</reactor.version>
确认修正

2019-06-20 08:37 UTC, shengxiang205 commented on pom.xml
> +                <artifactId>sofa-tracer-reactor-plugin</artifactId>
这个plugin要去除的, 我去除他

2019-06-20 08:38 UTC, shengxiang205 commented on sofa-tracer-plugins/sofa-tracer-webflux-plugin/pom.xml
> +            <artifactId>sofa-tracer-springmvc-plugin</artifactId>
复用度很高, 抽取一个sofa-tracer-web-base-plugin ?

2019-06-20 08:44 UTC, shengxiang205 commented on tracer-core/pom.xml
> +            <version>${reactor.version}</version>
已修正

2019-06-20 08:51 UTC, shengxiang205 commented on tracer-core/src/main/java/com/alipay/common/tracer/core/reactor/MonoSofaOperator.java
> +            new SofaTracerReactorSubscriber<>(actual, this.startSpan, this.finishSpan, true));
这个log是开发的时候debug用的, 先去掉了

2019-06-20 08:55 UTC, shengxiang205 commented on tracer-core/src/main/java/com/alipay/common/tracer/core/reactor/SofaTracerBarrier.java
> +            SofaTracerSpan newSpan = sofaTraceContext.getCurrentSpan();
这里就是newSpan, 因为在runnable被call过程中, 可能创建新的span, 这个需要拿出来保存到context里面, 这是确实是newSpan的语意

2019-06-20 09:19 UTC, glmapper commented on tracer-core/src/main/java/com/alipay/common/tracer/core/reactor/SofaTracerBarrier.java
> +            SofaTracerSpan newSpan = sofaTraceContext.getCurrentSpan();
> 这里就是newSpan, 因为在runnable被call过程中, 可能创建新的span, 这个需要拿出来保存到context里面, 这是确实是newSpan的语意

sofaTraceContext.getCurrentSpan() 是获取当前透传上下文的 span，newSpan 通常会是在 cs 或者 sr 阶段产生。所以建议这里 不使用newSpan

2019-07-01 06:05 UTC, glmapper requested changes

2019-07-01 06:05 UTC, glmapper commented on tracer-sofa-boot-starter/src/main/java/com/alipay/sofa/tracer/boot/springmvc/configuration/OpenTracingSpringMvcAutoConfiguration.java
>      }
HookRegisteringBeanDefinitionRegistryPostProcessor 的作用域应该不仅仅是在WebfluxSofaTracerFilterConfiguration 中，应该对于 reactor 组件生效，然后通过例如 com.alipay.sofa.tracer.reactor.enabled 来控制是否启用 reactor 组件的埋点

2019-07-01 06:05 UTC, glmapper commented on tracer-sofa-boot-starter/src/main/java/com/alipay/sofa/tracer/boot/springmvc/processor/HookRegisteringBeanDefinitionRegistryPostProcessor.java
> +import org.apache.commons.logging.LogFactory;
无用的引入可以移除掉

2019-07-01 06:05 UTC, glmapper commented on tracer-sofa-boot-starter/src/main/java/com/alipay/sofa/tracer/boot/springmvc/processor/HookRegisteringBeanDefinitionRegistryPostProcessor.java
> +import org.springframework.beans.factory.BeanFactory;
移除没有用到的引用

2019-07-01 06:05 UTC, glmapper commented on tracer-sofa-boot-starter/src/main/java/com/alipay/sofa/tracer/boot/springmvc/processor/HookRegisteringBeanDefinitionRegistryPostProcessor.java
> +import reactor.core.Scannable;
同上

2019-07-01 06:05 UTC, glmapper commented on tracer-sofa-boot-starter/src/main/java/com/alipay/sofa/tracer/boot/springmvc/processor/HookRegisteringBeanDefinitionRegistryPostProcessor.java
> +import reactor.util.context.Context;
同上

2019-07-01 06:05 UTC, glmapper commented on tracer-sofa-boot-starter/src/main/java/com/alipay/sofa/tracer/boot/springmvc/processor/HookRegisteringBeanDefinitionRegistryPostProcessor.java
> +import java.util.function.BooleanSupplier;
同上

2019-07-01 06:05 UTC, glmapper commented on tracer-sofa-boot-starter/src/main/java/com/alipay/sofa/tracer/boot/springmvc/processor/HookRegisteringBeanDefinitionRegistryPostProcessor.java
> +    private final ConfigurableApplicationContext context;
context 这里貌似没有什么具体的作用，是否可以考虑移除掉

2019-07-01 06:05 UTC, glmapper commented on tracer-sofa-boot-starter/src/main/java/com/alipay/sofa/tracer/boot/springmvc/configuration/OpenTracingSpringMvcAutoConfiguration.java
> +import reactor.core.publisher.Hooks;
无用引用

2019-07-03 08:45 UTC, ujjboy commented
Hi, @shengxiang205   can you split this PR into two smaller PR? One is about the feature, and another is about code format.

2019-07-04 07:57 UTC, guanchao-yang requested changes

2019-07-04 07:57 UTC, guanchao-yang commented on sofa-tracer-plugins/sofa-tracer-webflux-plugin/src/main/java/com/alipay/sofa/tracer/plugins/webflux/SpringWebfluxJsonStatReporter.java
> +     * 输出拼接器
新的代码注释中不要添加中文，建议都以 `English` 描述

2019-07-04 07:57 UTC, guanchao-yang commented on sofa-tracer-plugins/sofa-tracer-webflux-plugin/src/main/java/com/alipay/sofa/tracer/plugins/webflux/SpringWebfluxJsonStatReporter.java
> +            SelfLog.error("统计日志<" + statTracerName + ">输出异常", t);
换为 English 日志输出，还有注释也换为 English 吧。

2019-07-04 07:57 UTC, guanchao-yang commented on sofa-tracer-plugins/sofa-tracer-webflux-plugin/src/main/java/com/alipay/sofa/tracer/plugins/webflux/SpringWebfluxStatReporter.java
> +            SelfLog.error("统计日志<" + statTracerName + ">输出异常", t);
English

2019-07-04 07:57 UTC, guanchao-yang commented on tracer-sofa-boot-starter/pom.xml
> +            <artifactId>sofa-tracer-webflux-plugin</artifactId>
另外，`sofa-tracer-webflux-plugin` 模块下需要补充一个 `readme.md`描述对该插件的使用方式，可以参考下其他插件的编写方式哈。  @glmapper 正式发布后，使用文档也记得放到 RELEASE Notes 里面。

2019-07-04 07:57 UTC, guanchao-yang commented on sofa-tracer-plugins/sofa-tracer-zipkin-plugin/src/main/java/com/alipay/sofa/tracer/plugins/zipkin/adapter/ZipkinV2SpanAdapter.java
> +     *
这次怎么这么多代码格式化哈？之前的代码格式化的插件是有什么问题吗？如果有的话，格式化也建议单独一个 PR 哈。

2019-07-04 11:43 UTC, glmapper commented
@ujjboy @guanchao-yang all requested changes has been solved

2019-07-04 11:45 UTC, glmapper commented on tracer-sofa-boot-starter/pom.xml
> +            <artifactId>sofa-tracer-webflux-plugin</artifactId>
> 另外，`sofa-tracer-webflux-plugin` 模块下需要补充一个 `readme.md`描述对该插件的使用方式，可以参考下其他插件的编写方式哈。 @glmapper 正式发布后，使用文档也记得放到 RELEASE Notes 里面。

文档部分随着发布报告一起同步，@shengxiang205 可以参考 https://github.com/glmapper/tarcer-test-samples 这个工程将 README 补充下

2019-07-31 12:20 UTC, glmapper commented
@shengxiang205 本周计划先发布 2.4.1-SNAPSHOT 版本，这个 PR 你看下还是否有修改或者优化

2022-08-29 08:00 UTC, glmapper commented
这个 PR 暂时先关闭，历史问题，暂无驱动

2022-08-29 08:00 UTC, closed without merging