Add sample verification before reporting
sofastack/sofa-tracer pull request #297
Opened 2019-11-08 06:24 UTC by qingfeng-bi

### Motivation:

Explain the context, and why you're making that change.
To make others understand what is the problem you're trying to solve.

### Modification:

Describe the idea and modifications you've done.

### Result:

Fixes #<GitHub issue number>. 

If there is no issue then describe the changes introduced by this PR.

2019-11-08 08:18 UTC, glmapper requested changes

2019-11-08 08:18 UTC, glmapper commented on sofa-tracer-plugins/sofa-tracer-zipkin-plugin/src/main/java/com/alipay/sofa/tracer/plugins/zipkin/ZipkinSofaTracerSpanRemoteReporter.java
> +        }
不能用这种方式来判断的，正确的做法是通过 span.getSofaTracerSpanContext().isSampled() 这个来判断，这里只关注当前 span 是否需要上报即可

2019-11-08 09:01 UTC, qingfeng-bi commented on sofa-tracer-plugins/sofa-tracer-zipkin-plugin/src/main/java/com/alipay/sofa/tracer/plugins/zipkin/ZipkinSofaTracerSpanRemoteReporter.java
> +        }
好的，我改一下，谢谢。

2019-11-11 02:50 UTC, glmapper commented
@qingfeng-bi 我关联了两个 issue 在你这个 PR 里面，你可以看下。另外你这个 CI 没过看日志是格式问题，你需要本地先执行一下 mvn clean test，然后再补充下先关 test case

2019-11-11 11:14 UTC, qingfeng-bi commented
好的，我试一下，谢谢。

2019-11-11 12:50 UTC, qingfeng-bi commented
> 
> 
> @qingfeng-bi 我关联了两个 issue 在你这个 PR 里面，你可以看下。另外你这个 CI 没过看日志是格式问题，你需要本地先执行一下 mvn clean test，然后再补充下先关 test case

执行mvn clean test的时候，TimedRollingFileAppenderTest这个测试类报错：
Running com.alipay.common.tracer.core.appender.file.TimedRollingFileAppenderTest
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1.346 sec <<< FAILURE! - in com.alipay.common.tracer.core.appender.file.TimedRollingFileAppenderTest
test(com.alipay.common.tracer.core.appender.file.TimedRollingFileAppenderTest)  Time elapsed: 1.336 sec  <<< FAILURE!
java.lang.AssertionError: The number of files is incorrect. The number of files starting with rolling-test.log should be 2
        at com.alipay.common.tracer.core.appender.file.TimedRollingFileAppenderTest.test(TimedRollingFileAppenderTest.java:61)

Running com.alipay.common.tracer.core.appender.info.StaticInfoLogTest
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1.564 sec <<< FAILURE! - in com.alipay.common.tracer.core.appender.info.StaticInfoLogTest
testLogStaticInfo(com.alipay.common.tracer.core.appender.info.StaticInfoLogTest)  Time elapsed: 1.563 sec  <<< FAILURE!
java.lang.AssertionError: The contents of the 0 column in the log and parameters are inconsistent. The log is 35592;The parameter is 26172
        at com.alipay.common.tracer.core.base.AbstractTestBase.checkResult(AbstractTestBase.java:141)
        at com.alipay.common.tracer.core.appender.info.StaticInfoLogTest.testLogStaticInfo(StaticInfoLogTest.java:61)

2019-11-14 11:58 UTC, qingfeng-bi commented
> 
> 
> @qingfeng-bi 我关联了两个 issue 在你这个 PR 里面，你可以看下。另外你这个 CI 没过看日志是格式问题，你需要本地先执行一下 mvn clean test，然后再补充下先关 test case

现在执行mvn clean test 报错，core包里面的一个测试类有问题：
Running com.alipay.common.tracer.core.appender.file.TimedRollingFileAppenderTest
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1.947 sec <<< FAILURE! - in com.alipay.common.tracer.core.appender.file.TimedRollingFileAppenderTest
test(com.alipay.common.tracer.core.appender.file.TimedRollingFileAppenderTest)  Time elapsed: 1.947 sec  <<< FAILURE!
java.lang.AssertionError: The number of files is incorrect. The number of files starting with rolling-test.log should be 2
        at com.alipay.common.tracer.core.appender.file.TimedRollingFileAppenderTest.test(TimedRollingFileAppenderTest.java:61)

2019-11-15 06:12 UTC, closed without merging