Fixes gh-384
sofastack/sofa-tracer pull request #385
Opened 2020-09-13 15:15 UTC by chenmudu

### Motivation:

Support kafka mq in SOFATracer 3.1.X。

### Modification:

Support kafka mq in SOFATracer 3.1.X。

### Result:

Fixes #<gh-384>. 

add kafka mq plugin for SOFATracer 3.1.X。

2020-09-14 02:15 UTC, glmapper requested changes

2020-09-14 02:15 UTC, glmapper commented on sofa-tracer-plugins/sofa-tracer-kafkamq-plugin/src/test/java/com/sofa/tracer/plugins/kafka/KafkaTest.java
> +    }
这个用例的意义是？

2020-09-14 02:15 UTC, glmapper commented on sofa-tracer-plugins/sofa-tracer-kafkamq-plugin/src/test/java/com/sofa/tracer/plugins/kafka/base/MockSofaTracerConfiguration.java
> +
这里可以移除未使用到的代码

2020-09-14 02:15 UTC, glmapper commented on sofa-tracer-plugins/sofa-tracer-kafkamq-plugin/src/test/java/com/sofa/tracer/plugins/kafka/base/MockSofaTracerSpringKafkaTest.java
> +    //    public static EmbeddedKafkaRule embeddedKafka = new EmbeddedKafkaRule(2, true, 2, "spring");
pls remove

2020-09-14 02:15 UTC, glmapper commented on tracer-sofa-boot-starter/src/main/java/com/alipay/sofa/tracer/boot/kafka/configuration/SofaTracerKafkaAutoConfiguration.java
> +    public BeanPostProcessor kafkaConsumerFactoryPostProcessor() {
use  @ConditionOnMissingBean annotation to Control the creation of a bean

2020-09-14 02:15 UTC, glmapper commented on sofa-tracer-plugins/sofa-tracer-kafkamq-plugin/src/test/java/com/sofa/tracer/plugins/kafka/base/MockSofaTracerConfiguration.java
> +import org.springframework.kafka.core.*;
avoid use import xxx.*

2020-09-14 02:15 UTC, glmapper commented on sofa-tracer-plugins/sofa-tracer-kafkamq-plugin/src/main/java/com/sofa/alipay/tracer/plugins/kafkamq/consumer/SofaTracerKafkaConsumer.java
> +import org.apache.kafka.clients.consumer.*;
avoid use import xx.*

2020-09-14 02:16 UTC, glmapper commented
@chenmudu 如果使用了外部代码的引用，需要将其作者标注上去

2020-09-14 03:29 UTC, chenmudu commented
> @chenmudu 如果使用了外部代码的引用，需要将其作者标注上去

参考过open tracing官方的一些实现，我回头看下哪些可能相似，吧参考的作者名字加上。

2020-09-29 11:35 UTC, glmapper approved these changes
LGTM

2020-09-29 11:36 UTC, merged